application: gae-keijiban
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static

- url: /admin/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
